package com.skula.school.models;

import com.skula.school.services.DatabaseService;

public class Data {
	public static void insert(DatabaseService dbs) {
		String categoryId = "";
		String languageId = "";
		languageId = dbs.insertLanguage("GER");
		dbs.insertVerb("anbieten", "bietet an", "bot an", "hat angeboten", "offrir, proposer", languageId);
		dbs.insertVerb("anfangen", "fängt an", "fing an", "hat angefangen", "commencer", languageId);
		dbs.insertVerb("anziehen", "zieht an", "zog an", "hat angezogen", "mettre (vêtement)", languageId);
		dbs.insertVerb("aufgeben", "gibt auf", "gab auf", "hat aufgegeben", "abandonner", languageId);
		dbs.insertVerb("ausblasen", "bläst aus", "blies aus", "hat ausgeblasen", "souffler (bougie)", languageId);
		dbs.insertVerb("ausgeben", "gibt aus", "gab aus", "hat ausgegeben", "dépenser (argent)", languageId);
		dbs.insertVerb("aussehen", "sieht aus", "sah aus", "hat ausgesehen", "avoir l'air", languageId);
		dbs.insertVerb("ausziehen", "zieht aus", "zog aus", "hat ausgezogen", "enlever (vêtement)", languageId);
		dbs.insertVerb("ausziehen", "zieht aus", "zog aus", "ist ausgezogen", "déménager", languageId);
		dbs.insertVerb("backen", "bäckt", "backte / buk", "hat gebacken", "faire cuire au four(pâtisserie)", languageId);

		// ---- temps ------
		categoryId = dbs.insertCategory("Adv. de temps", languageId);
		dbs.insertWord("", "bald", "bientôt", categoryId);
		dbs.insertWord("", "bereits", "déjà", categoryId);
		dbs.insertWord("", "bisher", "jusqu'à  présent", categoryId);
		dbs.insertWord("", "danach", "après", categoryId);
		dbs.insertWord("", "davor", "avant", categoryId);
		dbs.insertWord("", "einst", "jadis", categoryId);
		dbs.insertWord("", "endlich", "enfin, à la fin", categoryId);
		dbs.insertWord("", "freitags", "le vendredi", categoryId);
		dbs.insertWord("", "gestern", "hier", categoryId);
		dbs.insertWord("", "immer", "toujours", categoryId);
		dbs.insertWord("", "inzwischen", "entre-temps", categoryId);
		dbs.insertWord("", "neulich", "récemment", categoryId);
		dbs.insertWord("", "nie", "jamais", categoryId);
		dbs.insertWord("", "oft", "souvent", categoryId);
		dbs.insertWord("", "regelmä$ig", "régulièrement", categoryId);
		dbs.insertWord("", "sofort", "tout de suite", categoryId);
		dbs.insertWord("", "stets", "constamment", categoryId);
		dbs.insertWord("", "täglich", "quotidiennement", categoryId);
		dbs.insertWord("", "zurzeit", "actuellement", categoryId);

		// ----- lieu -----
		categoryId = dbs.insertCategory("Adv. de lieu", languageId);
		dbs.insertWord("", "aufwärts", "vers le haut", categoryId);
		dbs.insertWord("", "au$en", "à  l'extérieur", categoryId);
		dbs.insertWord("", "da", "là", categoryId);
		dbs.insertWord("", "dort", "là-bas", categoryId);
		dbs.insertWord("", "drinnen", "à  l'intérieur", categoryId);
		dbs.insertWord("", "fort", "au loin", categoryId);
		dbs.insertWord("", "hier", "ici", categoryId);
		dbs.insertWord("", "hierhin", "(vers/jusqu'à) ici", categoryId);
		dbs.insertWord("", "hinein", "à l'intérieur", categoryId);
		dbs.insertWord("", "hinten", "derrière", categoryId);
		dbs.insertWord("", "irgendwo", "quelque part", categoryId);
		dbs.insertWord("", "links", "à gauche", categoryId);
		dbs.insertWord("", "nebenan", "à côté", categoryId);
		dbs.insertWord("", "oberhalb", "au-dessus", categoryId);
		dbs.insertWord("", "überall", "partout", categoryId);
		dbs.insertWord("", "unten", "au-dessous", categoryId);
		dbs.insertWord("", "vorn", "devant", categoryId);

		// ----- cause ------
		categoryId = dbs.insertCategory("Adv. de cause", languageId);
		dbs.insertWord("", "also", "ainsi, donc", categoryId);
		dbs.insertWord("", "anstandshalber", "par souci des convenances", categoryId);
		dbs.insertWord("", "dadurch", "par ce moyen", categoryId);
		dbs.insertWord("", "darum", "c'est pourquoi", categoryId);
		dbs.insertWord("", "demnach", "en conséquence", categoryId);
		dbs.insertWord("", "demzufolge", "par conséquent", categoryId);
		dbs.insertWord("", "deshalb", "pour cette raison, pour cela", categoryId);
		dbs.insertWord("", "folglich", "par conséquent", categoryId);
		dbs.insertWord("", "somit", "par conséquent", categoryId);

		// ----- coordination -----
		categoryId = dbs.insertCategory("Adv. de coordination", languageId);
		dbs.insertWord("", "au$erdem", "en outre", categoryId);
		dbs.insertWord("", "danach", "ensuite", categoryId);
		dbs.insertWord("", "deshalb", "pour cette raison, c'est pourquoi", categoryId);
		dbs.insertWord("", "folglich", "par consÃ©quent", categoryId);
		dbs.insertWord("", "schlie$lich", "finalement, après tout", categoryId);
		dbs.insertWord("", "trotzdem", "malgré tout", categoryId);
		dbs.insertWord("", "zuvor", "auparavant, avant", categoryId);

		// ----- maniere ------
		categoryId = dbs.insertCategory("Adv. de maniere", languageId);
		dbs.insertWord("", "anders", "autrement", categoryId);
		dbs.insertWord("", "äu$erst", "extrêmement", categoryId);
		dbs.insertWord("", "beinahe", "presque, quasi", categoryId);
		dbs.insertWord("", "bekanntlich", "comme chacun sait", categoryId);
		dbs.insertWord("", "ebenfalls", "aussi", categoryId);
		dbs.insertWord("", "fast", "presque", categoryId);
		dbs.insertWord("", "folgenderma$en", "de la manière suivante", categoryId);
		dbs.insertWord("", "ganz", "tout, entièrement", categoryId);
		dbs.insertWord("", "genauso", "de même", categoryId);
		dbs.insertWord("", "genug", "assez", categoryId);
		dbs.insertWord("", "gern", "volontiers", categoryId);
		dbs.insertWord("", "grö$tenteils", "en majeure partie, majoritairement", categoryId);
		dbs.insertWord("", "hauptsächlich", "surtout", categoryId);
		dbs.insertWord("", "kaum", "guère, à  peine", categoryId);
		dbs.insertWord("", "leider", "malheureusement", categoryId);
		dbs.insertWord("", "möglicherweise", "peut-être", categoryId);
		dbs.insertWord("", "reihenweise", "les uns après les autres", categoryId);
		dbs.insertWord("", "sehr", "très", categoryId);
		dbs.insertWord("", "so", "ainsi", categoryId);
		dbs.insertWord("", "vielleicht", "peut-être", categoryId);
		dbs.insertWord("", "wirklich", "vraiment", categoryId);

		// voc 1
		categoryId = dbs.insertCategory("L'identité", languageId);
		dbs.insertWord("die", "Adresse (n)", "l'adresse", categoryId);
		dbs.insertWord("", "allein", "seul", categoryId);
		dbs.insertWord("das", "Alter (-)", "l’âge", categoryId);
		dbs.insertWord("die", "Anschrift (en)", "l'adresse", categoryId);
		dbs.insertWord("das", "Ausland", "le pays étranger", categoryId);
		dbs.insertWord("der", "Ausländer (-)", "l’étranger", categoryId);
		dbs.insertWord("der", "Ausweis (e)", "la carte d'identité", categoryId);
		dbs.insertWord("der", "Beruf (e)", "le métier", categoryId);
		dbs.insertWord("der", "Bruder (¨)", "le frère", categoryId);
		dbs.insertWord("der/die", "Deutsche (n)", "l'Allemand(e)", categoryId);
		dbs.insertWord("", "dreisprachig", "trilingue", categoryId);
		dbs.insertWord("das", "Einzelkind (er)", "l’enfant unique", categoryId);
		dbs.insertWord("", "Eltern (PLUR)", "les parents", categoryId);
		dbs.insertWord("die", "E-Mail-Adresse (n)", "l'adresse électronique", categoryId);
		dbs.insertWord("das", "Enkelkind (er)", "le petit-fils", categoryId);
		dbs.insertWord("der/die", "Erwachsene (n)", "adulte", categoryId);
		dbs.insertWord("die", "Familie (n)", "la famille", categoryId);
		dbs.insertWord("der", "Familienname (n)", "le nom de famille", categoryId);
		dbs.insertWord("der", "Fragebogen (-)", "le questionnaire", categoryId);
		dbs.insertWord("der", "Franzose (n)", "le Français", categoryId);
		dbs.insertWord("die", "Französin (nen)", "la Française", categoryId);
		dbs.insertWord("die", "Frau (en)", "la femme", categoryId);
		dbs.insertWord("die", "Fremdsprache (n)", "la langue étrangère", categoryId);
		dbs.insertWord("der", "Führerschein (e)", "le permis de conduire", categoryId);
		dbs.insertWord("", "geboren", "né", categoryId);
		dbs.insertWord("der", "Geburtsort (e)", "lieu de naissance", categoryId);
		dbs.insertWord("", "geschieden", "divorcé", categoryId);
		dbs.insertWord("", "Geschwister (PLUR)", "frère(s) et soeur(s)", categoryId);
		dbs.insertWord("", "getrennt", "séparé", categoryId);
		dbs.insertWord("", "Gro$eltern (PLUR)", "les grands-parents", categoryId);
		dbs.insertWord("die", "Gro$mutter (¨)", "la grand-mère", categoryId);
		dbs.insertWord("der", "Gro$vater (¨)", "le grand-père", categoryId);
		dbs.insertWord("die", "Handynummer (n)", "le numéro", categoryId);
		dbs.insertWord("die", "Hausnummer (n)", "le numéro de la maison", categoryId);
		dbs.insertWord("", "hei$en", "s'appeler", categoryId);
		dbs.insertWord("der/die", "Jugendliche (n)", "le jeune", categoryId);
		dbs.insertWord("der", "Junge (n)", "le garçon", categoryId);
		dbs.insertWord("das", "Kind (er)", "l’enfant", categoryId);
		dbs.insertWord("das", "Land (¨er)", "le pays", categoryId);
		dbs.insertWord("", "leben", "vivre", categoryId);
		dbs.insertWord("der", "Lebenslauf (¨e)", "le C.V.", categoryId);
		dbs.insertWord("", "ledig", "célibataire", categoryId);
		dbs.insertWord("das", "Mädchen (-)", "la fillette, la jeune fille", categoryId);
		dbs.insertWord("der", "Mann (¨er)", "l’homme", categoryId);
		dbs.insertWord("die", "Mutter (¨)", "la mère", categoryId);
		dbs.insertWord("die", "Muttersprache (n)", "la langue maternelle", categoryId);
		dbs.insertWord("der", "Nachname (n)", "le nom de famille", categoryId);
		dbs.insertWord("der", "Name (n)", "le nom", categoryId);
		dbs.insertWord("", "nennen", "nommer, citer", categoryId);
		dbs.insertWord("die", "Oma (s)", "la mamie", categoryId);
		dbs.insertWord("der", "Onkel (s)", "l’oncle", categoryId);
		dbs.insertWord("der", "Opa (s)", "le papi", categoryId);
		dbs.insertWord("der", "Österreicher (-)", "l’Autrichien", categoryId);
		dbs.insertWord("die", "Papiere", "les papiers d'identité", categoryId);
		dbs.insertWord("der", "Pass (¨e)", "le passeport", categoryId);
		dbs.insertWord("die", "Postleitzahl (en)", "le code postal", categoryId);
		dbs.insertWord("der", "Schweizer (-)", "la Suisse", categoryId);
		dbs.insertWord("die", "Schwester (n)", "la soeur", categoryId);
		dbs.insertWord("der", "Sohn (¨e)", "le fils", categoryId);
		dbs.insertWord("der", "Staatsbürger (-)", "le citoyen", categoryId);
		dbs.insertWord("die", "Stadt (¨e)", "la ville", categoryId);
		dbs.insertWord("der", "Stammbaum (¨e)", "l’arbre généalogique", categoryId);
		dbs.insertWord("der", "Steckbrief (e) (ici)", "la fiche signalétique", categoryId);
		dbs.insertWord("die", "Stra$e (n)", "la rue", categoryId);
		dbs.insertWord("die", "Tante (n)", "la tante", categoryId);
		dbs.insertWord("die", "Telefonnummer (n)", "le numéro de téléphone", categoryId);
		dbs.insertWord("die", "Tochter (¨)", "la fille", categoryId);
		dbs.insertWord("die", "Unterschrift (en)", "la signature", categoryId);
		dbs.insertWord("der", "Vater (¨)", "le père", categoryId);
		dbs.insertWord("", "verheiratet", "marié", categoryId);
		dbs.insertWord("", "verwandt (sein)", "avoir un lien de parenté", categoryId);
		dbs.insertWord("der/die", "Verwandte (n)", "le parent", categoryId);
		dbs.insertWord("die", "Verwandtschaft (en)", "la famille", categoryId);
		dbs.insertWord("der", "Vorname (n)", "le prénom", categoryId);
		dbs.insertWord("", "vorstellen (sich)", "(se) présenter", categoryId);
		dbs.insertWord("", "wohnen", "habiter", categoryId);
		dbs.insertWord("der", "Wohnort (e)", "lieu de résidence", categoryId);
		dbs.insertWord("", "zweisprachig", "bilingue", categoryId);
		dbs.insertWord("die", "Zwillinge", "les jumeaux", categoryId);

		categoryId = dbs.insertCategory("La personnalité", languageId);
		dbs.insertWord("", "ähnlich", "semblable, ressemblant", categoryId);
		dbs.insertWord("die", "Ähnlichkeit", "la ressemblance", categoryId);
		dbs.insertWord("", "albern", "puéril, idiot", categoryId);
		dbs.insertWord("", "alt", "vieux", categoryId);
		dbs.insertWord("", "arm", "pauvre", categoryId);
		dbs.insertWord("", "arm", "malheureux", categoryId);
		dbs.insertWord("das", "Auge (n)", "l'oeil", categoryId);
		dbs.insertWord("", "aussehen", "avoir l'air", categoryId);
		dbs.insertWord("das", "Aussehen (-)", "l'apparence physique", categoryId);
		dbs.insertWord("", "begabt", "doué", categoryId);
		dbs.insertWord("", "bekannt", "connu", categoryId);
		dbs.insertWord("", "beliebt", "apprécié", categoryId);
		dbs.insertWord("", "bescheiden", "modeste", categoryId);
		dbs.insertWord("", "blond", "blond", categoryId);
		dbs.insertWord("", "böse", "méchant", categoryId);
		dbs.insertWord("", "brav", "sage, raisonnable", categoryId);
		dbs.insertWord("die", "Brille (n)", "les lunettes", categoryId);
		dbs.insertWord("die", "Charaktereigenschaft", "(entr)ait de caractère", categoryId);
		dbs.insertWord("", "dick", "gros", categoryId);
		dbs.insertWord("", "dunkel", "sombre, foncé", categoryId);
		dbs.insertWord("", "dünn", "mince", categoryId);
		dbs.insertWord("", "ehrlich", "honnête", categoryId);
		dbs.insertWord("die", "Eigenschaft (en)", "la qualité, la particularité", categoryId);
		dbs.insertWord("", "empfindlich", "susceptible, sensible", categoryId);
		dbs.insertWord("", "energisch", "énergique, vif", categoryId);
		dbs.insertWord("", "ernst", "sérieux", categoryId);
		dbs.insertWord("", "faul", "paresseux", categoryId);
		dbs.insertWord("", "flei$ig", "travailleur, zélé, assidu", categoryId);
		dbs.insertWord("", "frech", "insolent", categoryId);
		dbs.insertWord("der", "Freund (e)", "l'ami", categoryId);
		dbs.insertWord("", "freundlich", "aimable, amical", categoryId);
		dbs.insertWord("die", "Frisur (en)", "la coiffure", categoryId);
		dbs.insertWord("", "geduldig", "patient", categoryId);
		dbs.insertWord("", "gemein", "méchant, odieux", categoryId);
		dbs.insertWord("", "gepflegt", "soigné, bien mis", categoryId);
		dbs.insertWord("", "gerecht", "juste", categoryId);
		dbs.insertWord("", "geschickt", "adroit", categoryId);
		dbs.insertWord("", "glücklich", "heureux", categoryId);
		dbs.insertWord("", "grau", "gris", categoryId);
		dbs.insertWord("", "gro$", "grand", categoryId);
		dbs.insertWord("", "gut", "bien, bon", categoryId);
		dbs.insertWord("", "das Haar (e)", "le(s) cheveu(x)", categoryId);
		dbs.insertWord("", "hart", "dur", categoryId);
		dbs.insertWord("", "hässlich", "laid", categoryId);
		dbs.insertWord("", "hell", "clair", categoryId);
		dbs.insertWord("", "hilfsbereit", "serviable", categoryId);
		dbs.insertWord("das", "Hobby (Hobbys)", "le loisir préféré", categoryId);
		dbs.insertWord("", "höflich", "poli", categoryId);
		dbs.insertWord("", "hübsch", "joli", categoryId);
		dbs.insertWord("", "humorvoll", "plein d'humour", categoryId);
		dbs.insertWord("", "interessieren (sich)", "s'intéresser à ", categoryId);
		dbs.insertWord("", "interessiert", "intéressé", categoryId);
		dbs.insertWord("", "jugendlich", "adolescent", categoryId);
		dbs.insertWord("", "jung", "jeune", categoryId);
		dbs.insertWord("", "klein", "petit", categoryId);
		dbs.insertWord("", "klug", "intelligent", categoryId);
		dbs.insertWord("", "komisch", "drôle", categoryId);
		dbs.insertWord("", "kontaktfreudig", "qui aime les contacts", categoryId);
		dbs.insertWord("", "kräftig", "fort", categoryId);
		dbs.insertWord("", "lächerlich", "ridicule", categoryId);
		dbs.insertWord("", "lieb", "gentil", categoryId);
		dbs.insertWord("", "lustig", "drôle, gai", categoryId);
		dbs.insertWord("", "mutig", "courageux", categoryId);
		dbs.insertWord("", "naiv", "naïf", categoryId);
		dbs.insertWord("", "nervös", "nerveux", categoryId);
		dbs.insertWord("", "nett", "gentil", categoryId);
		dbs.insertWord("", "neugierig", "curieux", categoryId);
		dbs.insertWord("", "ordentlich", "soigneux", categoryId);
		dbs.insertWord("der", "Pechvogel", "le malchanceux", categoryId);
		dbs.insertWord("die", "Persönlichkeit (en)", "la personnalité", categoryId);
		dbs.insertWord("", "reich", "riche", categoryId);
		dbs.insertWord("", "ruhig", "tranquille, calme", categoryId);
		dbs.insertWord("", "schlank", "mince", categoryId);
		dbs.insertWord("", "schlau", "malin, intelligent", categoryId);
		dbs.insertWord("", "schmal", "étroit", categoryId);
		dbs.insertWord("", "schön", "beau", categoryId);
		dbs.insertWord("", "schüchtern", "timide", categoryId);
		dbs.insertWord("", "schwach", "faible", categoryId);
		dbs.insertWord("", "schwarz", "noir", categoryId);
		dbs.insertWord("", "selbstsicher", "sûr de soi", categoryId);
		dbs.insertWord("", "sportlich", "sportif", categoryId);
		dbs.insertWord("", "stark", "fort", categoryId);
		dbs.insertWord("", "der Steckbrief (e)", "(ici) la fiche signalétique", categoryId);
		dbs.insertWord("", "stolz", "fier", categoryId);
		dbs.insertWord("", "streng", "sévère", categoryId);
		dbs.insertWord("", "sü$", "mignon, gentil, touchant", categoryId);
		dbs.insertWord("", "sympathisch", "sympathique", categoryId);
		dbs.insertWord("", "tolerant", "tolérant", categoryId);
		dbs.insertWord("", "treu", "fidèle, loyal", categoryId);
		dbs.insertWord("", "unternehmungslustig", "entreprenant", categoryId);
		dbs.insertWord("", "unverschämt", "effronté, impertinent", categoryId);
		dbs.insertWord("", "vergesslich", "oublieux, distrait", categoryId);
		dbs.insertWord("", "vernünftig", "raisonnable", categoryId);
		dbs.insertWord("", "verständnisvoll", "compréhensif", categoryId);
		dbs.insertWord("", "das Vorbild (er)", "le modèle", categoryId);
		dbs.insertWord("", "vorsichtig", "prudent", categoryId);
		dbs.insertWord("", "weich", "sensible", categoryId);
		dbs.insertWord("", "wei$", "blanc", categoryId);
		dbs.insertWord("", "witzig", "drôle", categoryId);
		dbs.insertWord("", "zufrieden", "satisfait, content", categoryId);
		dbs.insertWord("", "zuverlässig", "fiable", categoryId);

		languageId = dbs.insertLanguage("ENG");
		dbs.insertVerb("abide", "abide", "abode", "abode", "respecter / se conformer à", languageId);
		dbs.insertVerb("arise", "arise", "arose", "arisen", "survenir", languageId);
		dbs.insertVerb("awake", "awake", "awoke", "awoken", "se réveiller", languageId);
		dbs.insertVerb("be", "be", "was, were", "been", "être", languageId);
		dbs.insertVerb("bear", "bear", "bore", "borne / born", "porter / supporter / naître", languageId);
		dbs.insertVerb("beat", "beat", "beat", "beaten", "battre", languageId);
		dbs.insertVerb("become", "become", "became", "become", "devenir", languageId);
		dbs.insertVerb("beget", "beget", "begat / begot", "begotten", "engendrer", languageId);
		dbs.insertVerb("begin", "begin", "began", "begun", "commencer", languageId);
		dbs.insertVerb("bend", "bend", "bent", "bent", "plier / se courber", languageId);
		dbs.insertVerb("bereave", "bereave", "bereft / bereaved", "bereft / bereaved", "déposséder / priver",
				languageId);
		dbs.insertVerb("bet", "bet", "bet", "bet", "parier", languageId);
		dbs.insertVerb("bid", "bid", "bid / bade", "bid / bidden", "offrir", languageId);
		dbs.insertVerb("bleed", "bleed", "bled", "bled", "saigner", languageId);
		dbs.insertVerb("blow", "blow", "blew", "blown", "souffler / gonfler", languageId);
		dbs.insertVerb("break", "break", "broke", "broken", "casser", languageId);
		dbs.insertVerb("breed", "breed", "bred", "bred", "élever (des animaux)", languageId);
		dbs.insertVerb("bring", "bring", "brought", "brought", "apporter", languageId);
		dbs.insertVerb("broadcast", "broadcast", "broadcast", "broadcast", "diffuser / émettre", languageId);
		dbs.insertVerb("build", "build", "built", "built", "construire", languageId);
		dbs.insertVerb("burn", "burn", "burnt / burned", "burnt / burned", "brûler", languageId);
		dbs.insertVerb("burst", "burst", "burst", "burst", "éclater", languageId);
		dbs.insertVerb("buy", "buy", "bought", "bought", "acheter", languageId);
		dbs.insertVerb("can", "can", "could", "could", "pouvoir", languageId);
		dbs.insertVerb("cast", "cast", "cast", "cast", "jeter / distribuer (rôles)", languageId);
		dbs.insertVerb("catch", "catch", "caught", "caught", "attraper", languageId);
		dbs.insertVerb("chide", "chide", "chid", "chiden", "gronder", languageId);
		dbs.insertVerb("choose", "choose", "chose", "chosen", "choisir", languageId);
		dbs.insertVerb("cling", "cling", "clung", "clung", "s'accrocher", languageId);
		dbs.insertVerb("clothe", "clothe", "clad / clothed", "clad / clothed", "habiller / recouvrir", languageId);
		dbs.insertVerb("come", "come", "came", "come", "venir", languageId);
		dbs.insertVerb("cost", "cost", "cost", "cost", "coûter", languageId);
		dbs.insertVerb("creep", "creep", "crept", "crept", "ramper", languageId);
		dbs.insertVerb("cut", "cut", "cut", "cut", "couper", languageId);
		dbs.insertVerb("deal", "deal", "dealt", "dealt", "distribuer", languageId);
		dbs.insertVerb("dig", "dig", "dug", "dug", "creuser", languageId);
		dbs.insertVerb("dive", "dive", "dived", "dived / dove", "plonger", languageId);
		dbs.insertVerb("do", "do", "did", "done", "faire", languageId);
		dbs.insertVerb("draw", "draw", "drew", "drawn", "dessiner / tirer", languageId);
		dbs.insertVerb("dream", "dream", "dreamt / dreamed", "dreamt / dreamed", "rêver", languageId);
		dbs.insertVerb("drink", "drink", "drank", "drunk", "boire", languageId);
		dbs.insertVerb("drive", "drive", "drove", "driven", "conduire", languageId);
		dbs.insertVerb("dwell", "dwell", "dwelt", "dwelt / dwelled", "habiter", languageId);
		dbs.insertVerb("eat", "eat", "ate", "eaten", "manger", languageId);
		dbs.insertVerb("fall", "fall", "fell", "fallen", "tomber", languageId);
		dbs.insertVerb("feed", "feed", "fed", "fed", "nourrir", languageId);
		dbs.insertVerb("feel", "feel", "felt", "felt", "se sentir / ressentir", languageId);
		dbs.insertVerb("fight", "fight", "fought", "fought", "se battre", languageId);
		dbs.insertVerb("find", "find", "found", "found", "trouver", languageId);
		dbs.insertVerb("flee", "flee", "fled", "fled", "s'enfuir", languageId);
		dbs.insertVerb("fling", "fling", "flung", "flung", "lancer", languageId);
		dbs.insertVerb("fly", "fly", "flew", "flown", "voler", languageId);
		dbs.insertVerb("forbid", "forbid", "forbade", "forbidden", "interdire", languageId);
		dbs.insertVerb("forecast", "forecast", "forecast", "forecast", "prévoir", languageId);
		dbs.insertVerb("foresee", "foresee", "foresaw", "foreseen", "prévoir / présentir", languageId);
		dbs.insertVerb("forget", "forget", "forgot", "forgotten / forgot", "oublier", languageId);
		dbs.insertVerb("forgive", "forgive", "forgave", "forgiven", "pardonner", languageId);
		dbs.insertVerb("forsake", "forsake", "forsook", "forsaken", "abandonner", languageId);
		dbs.insertVerb("freeze", "freeze", "froze", "frozen", "geler", languageId);
		dbs.insertVerb("get", "get", "got", "gotten / got", "obtenir", languageId);
		dbs.insertVerb("give", "give", "gave", "given", "donner", languageId);
		dbs.insertVerb("go", "go", "went", "gone", "aller", languageId);
		dbs.insertVerb("grind", "grind", "ground", "ground", "moudre / opprimer", languageId);
		dbs.insertVerb("grow", "grow", "grew", "grown", "grandir / pousser", languageId);
		dbs.insertVerb("hang", "hang", "hung", "hung", "tenir / pendre", languageId);
		dbs.insertVerb("have", "have", "had", "had", "avoir", languageId);
		dbs.insertVerb("hear", "hear", "heard", "heard", "entendre", languageId);
		dbs.insertVerb("hide", "hide", "hid", "hidden", "cacher", languageId);
		dbs.insertVerb("hit", "hit", "hit", "hit", "taper / appuyer", languageId);
		dbs.insertVerb("hold", "hold", "held", "held", "tenir", languageId);
		dbs.insertVerb("hurt", "hurt", "hurt", "hurt", "blesser", languageId);
		dbs.insertVerb("keep", "keep", "kept", "kept", "garder", languageId);
		dbs.insertVerb("kneel", "kneel", "knelt / knelled", "knelt / kneeled", "s'agenouiller", languageId);
		dbs.insertVerb("know", "know", "knew", "known", "connaître / savoir", languageId);
		dbs.insertVerb("lay", "lay", "laid", "laid", "poser", languageId);
		dbs.insertVerb("lead", "lead", "led", "led", "mener / guider", languageId);
		dbs.insertVerb("lean", "lean", "leant / leaned", "leant / leaned", "s'incliner / se pencher", languageId);
		dbs.insertVerb("leap", "leap", "leapt / leaped", "leapt / leaped", "sauter / bondir", languageId);
		dbs.insertVerb("learn", "learn", "learnt", "learnt", "apprendre", languageId);
		dbs.insertVerb("leave", "leave", "left", "left", "laisser / quitter / partir", languageId);
		dbs.insertVerb("lend", "lend", "lent", "lent", "prêter", languageId);
		dbs.insertVerb("let", "let", "let", "let", "permettre / louer", languageId);
		dbs.insertVerb("lie", "lie", "lay", "lain", "s'allonger", languageId);
		dbs.insertVerb("light", "light", "lit / lighted", "lit / lighted", "allumer", languageId);
		dbs.insertVerb("lose", "lose", "lost", "lost", "perdre", languageId);
		dbs.insertVerb("make", "make", "made", "made", "fabriquer", languageId);
		dbs.insertVerb("mean", "mean", "meant", "meant", "signifier", languageId);
		dbs.insertVerb("meet", "meet", "met", "met", "rencontrer", languageId);
		dbs.insertVerb("mow", "mow", "mowed", "mowed / mown", "tondre", languageId);
		dbs.insertVerb("offset", "offset", "offset", "offset", "compenser", languageId);
		dbs.insertVerb("overcome", "overcome", "overcame", "overcome", "surmonter", languageId);
		dbs.insertVerb("partake", "partake", "partook", "partaken", "prendre part à", languageId);
		dbs.insertVerb("pay", "pay", "paid", "paid", "payer", languageId);
		dbs.insertVerb("plead", "plead", "pled / pleaded", "pled / pleaded", "supplier / plaider", languageId);
		dbs.insertVerb("preset", "preset", "preset", "preset", "programmer", languageId);
		dbs.insertVerb("prove", "prove", "proved", "proven / proved", "prouver", languageId);
		dbs.insertVerb("put", "put", "put", "put", "mettre", languageId);
		dbs.insertVerb("quit", "quit", "quit", "quit", "quitter", languageId);
		dbs.insertVerb("read", "read", "read", "read", "lire", languageId);
		dbs.insertVerb("relay", "relay", "relaid", "relaid", "relayer", languageId);
		dbs.insertVerb("rend", "rend", "rent", "rent", "déchirer", languageId);
		dbs.insertVerb("rid", "rid", "rid", "rid", "débarrasser", languageId);
		dbs.insertVerb("ride", "ride", "rode", "ridden", "monter (vélo, cheval)", languageId);
		dbs.insertVerb("ring", "ring", "rang", "rung", "sonner / téléphoner", languageId);
		dbs.insertVerb("rise", "rise", "rose", "risen", "lever", languageId);
		dbs.insertVerb("run", "run", "ran", "run", "courir", languageId);
		dbs.insertVerb("saw", "saw", "saw / sawed", "sawn / sawed", "scier", languageId);
		dbs.insertVerb("say", "say", "said", "said", "dire", languageId);
		dbs.insertVerb("see", "see", "saw", "seen", "voir", languageId);
		dbs.insertVerb("seek", "seek", "sought", "sought", "chercher", languageId);
		dbs.insertVerb("sell", "sell", "sold", "sold", "vendre", languageId);
		dbs.insertVerb("send", "send", "sent", "sent", "envoyer", languageId);
		dbs.insertVerb("set", "set", "set", "set", "fixer", languageId);
		dbs.insertVerb("shake", "shake", "shook", "shaken", "secouer", languageId);
		dbs.insertVerb("shed", "shed", "shed", "shed", "répandre / laisser tomber", languageId);
		dbs.insertVerb("shine", "shine", "shone", "shone", "briller", languageId);
		dbs.insertVerb("shoe", "shoe", "shod", "shod", "chausser", languageId);
		dbs.insertVerb("shoot", "shoot", "shot", "shot", "tirer / fusiller", languageId);
		dbs.insertVerb("show", "show", "showed", "shown", "montrer", languageId);
		dbs.insertVerb("shut", "shut", "shut", "shut", "fermer", languageId);
		dbs.insertVerb("sing", "sing", "sang", "sung", "chanter", languageId);
		dbs.insertVerb("sink", "sink", "sank / sunk", "sunk / sunken", "couler", languageId);
		dbs.insertVerb("sit", "sit", "sat", "sat", "s'asseoir", languageId);
		dbs.insertVerb("slay", "slay", "slew", "slain", "tuer", languageId);
		dbs.insertVerb("sleep", "sleep", "slept", "slept", "dormir", languageId);
		dbs.insertVerb("slide", "slide", "slid", "slid", "glisser", languageId);
		dbs.insertVerb("slink", "slink", "slunk / slinked", "slunk / slinked", "s'en aller furtivement", languageId);
		dbs.insertVerb("slit", "slit", "slit", "slit", "fendre", languageId);
		dbs.insertVerb("smell", "smell", "smelt", "smelt", "sentir", languageId);
		dbs.insertVerb("sow", "sow", "sowed", "sown / sowed", "semer", languageId);
		dbs.insertVerb("speak", "speak", "spoke", "spoken", "parler", languageId);
		dbs.insertVerb("speed", "speed", "sped", "sped", "aller vite", languageId);
		dbs.insertVerb("spell", "spell", "spelt", "spelt", "épeler / orthographier", languageId);
		dbs.insertVerb("spend", "spend", "spent", "spent", "dépenser / passer du temps", languageId);
		dbs.insertVerb("spill", "spill", "spilt / spilled", "spilt / spilled", "renverser", languageId);
		dbs.insertVerb("spin", "spin", "spun", "spun", "tourner / faire tourner", languageId);
		dbs.insertVerb("spit", "spit", "spat / spit", "spat / spit", "cracher", languageId);
		dbs.insertVerb("split", "split", "split", "split", "fendre", languageId);
		dbs.insertVerb("spoil", "spoil", "spoilt", "spoilt", "gâcher / gâter", languageId);
		dbs.insertVerb("spread", "spread", "spread", "spread", "répandre", languageId);
		dbs.insertVerb("spring", "spring", "sprang", "sprung", "surgir / jaillir / bondir", languageId);
		dbs.insertVerb("stand", "stand", "stood", "stood", "être debout", languageId);
		dbs.insertVerb("steal", "steal", "stole", "stolen", "voler / dérober", languageId);
		dbs.insertVerb("stick", "stick", "stuck", "stuck", "coller", languageId);
		dbs.insertVerb("sting", "sting", "stung", "stung", "piquer", languageId);
		dbs.insertVerb("stink", "stink", "stank", "stunk", "puer", languageId);
		dbs.insertVerb("strew", "strew", "strewed", "strewn / strewed", "éparpiller", languageId);
		dbs.insertVerb("strike", "strike", "struck", "stricken / struck", "frapper", languageId);
		dbs.insertVerb("strive", "strive", "strove", "striven", "s'efforcer", languageId);
		dbs.insertVerb("swear", "swear", "swore", "sworn", "jurer", languageId);
		dbs.insertVerb("sweat", "sweat", "sweat / sweated", "sweat / sweated", "suer", languageId);
		dbs.insertVerb("sweep", "sweep", "swept", "swept", "balayer", languageId);
		dbs.insertVerb("swell", "swell", "swelled", "swollen / swelled", "gonfler / enfler", languageId);
		dbs.insertVerb("swim", "swim", "swam", "swum", "nager", languageId);
		dbs.insertVerb("swing", "swing", "swung", "swung", "se balancer", languageId);
		dbs.insertVerb("take", "take", "took", "taken", "prendre", languageId);
		dbs.insertVerb("teach", "teach", "taught", "taught", "enseigner", languageId);
		dbs.insertVerb("tear", "tear", "tore", "torn", "déchirer", languageId);
		dbs.insertVerb("tell", "tell", "told", "told", "dire / raconter", languageId);
		dbs.insertVerb("think", "think", "thought", "thought", "penser", languageId);
		dbs.insertVerb("thrive", "thrive", "throve / thrived", "thriven / thrived", "prospérer", languageId);
		dbs.insertVerb("throw", "throw", "threw", "thrown", "jeter", languageId);
		dbs.insertVerb("thrust", "thrust", "thrust", "thrust", "enfoncer", languageId);
		dbs.insertVerb("tread", "tread", "trod", "trodden", "piétiner quelque chose", languageId);
		dbs.insertVerb("typeset", "typeset", "typeset", "typeset", "composer", languageId);
		dbs.insertVerb("undergo", "undergo", "underwent", "undergone", "subir", languageId);
		dbs.insertVerb("understand", "understand", "understood", "understood", "comprendre", languageId);
		dbs.insertVerb("wake", "wake", "woke", "woken", "réveiller", languageId);
		dbs.insertVerb("wear", "wear", "wore", "worn", "porter (avoir sur soi)", languageId);
		dbs.insertVerb("weep", "weep", "wept", "wept", "pleurer", languageId);
		dbs.insertVerb("wet", "wet", "wet / wetted", "wet / wetted", "mouiller", languageId);
		dbs.insertVerb("win", "win", "won", "won", "gagner", languageId);
		dbs.insertVerb("wind", "wind", "wound", "wound", "enrouler / remonter", languageId);
		dbs.insertVerb("withdraw", "withdraw", "withdrew", "withdrawn", "se retirer", languageId);
		dbs.insertVerb("wring", "wring", "wrung", "wrung", "tordre", languageId);
		dbs.insertVerb("write", "write", "wrote", "written", "écrire", languageId);

		categoryId = dbs.insertCategory("Correspondance", languageId);
		dbs.insertWord("", "As agreed", "Comme convenu", categoryId);
		dbs.insertWord("", "Following", "En réponse à", categoryId);
		dbs.insertWord("", "Further to", "En réponse à", categoryId);
		dbs.insertWord("", "Regarding", "En ce qui concerne", categoryId);
		dbs.insertWord("", "With regard to", "En ce qui concerne", categoryId);

		categoryId = dbs.insertCategory("Entreprise", languageId);
		dbs.insertWord("", "Deadline", "Délai", categoryId);
		dbs.insertWord("", "Supplier", "Fournisseur", categoryId);
		dbs.insertWord("", "Manager", "Responsable", categoryId);
		dbs.insertWord("", "Company", "Société", categoryId);
		dbs.insertWord("", "Market research", "étude de marché", categoryId);
		dbs.insertWord("", "Brand", "marque", categoryId);
		dbs.insertWord("", "Brand awareness", "notoriété de la marque", categoryId);
		dbs.insertWord("", "Own-label brand", "marque de distributeur", categoryId);
		dbs.insertWord("", "Brand leader", "produit leader", categoryId);
		dbs.insertWord("", "Product range", "gamme de produit", categoryId);
		dbs.insertWord("", "Loss leader", "produit d'appel", categoryId);
		dbs.insertWord("", "Discount", "remise", categoryId);
		dbs.insertWord("", "Margin", "marge", categoryId);
		dbs.insertWord("", "Launch price", "prix de lancement", categoryId);
		dbs.insertWord("", "Leaflet", "dépliant", categoryId);
		dbs.insertWord("", "Factory outlet", "magasin d'usine", categoryId);
		dbs.insertWord("", "Manufacturer", "fabricant", categoryId);
		dbs.insertWord("", "Retail outlet", "point de vente", categoryId);
		dbs.insertWord("", "Wholesaler", "grossiste", categoryId);
		dbs.insertWord("", "Sales figures", "chiffres des ventes", categoryId);
		dbs.insertWord("", "Competition", "jeu concours", categoryId);
		dbs.insertWord("", "Focus group", "groupe d'étude", categoryId);

		categoryId = dbs.insertCategory("Téléphone", languageId);
		dbs.insertWord("", "Cell (phone)", "(Téléphone) portable", categoryId);
		dbs.insertWord("", "Mobile (phone)", "(Téléphone) portable", categoryId);
		dbs.insertWord("", "To dial a number", "Composer un numéro", categoryId);
		dbs.insertWord("", "To pick up the phone", "Décrocher le téléphone", categoryId);
		dbs.insertWord("", "To ring somebody (up)", "Téléphoner à quelqu'un", categoryId);
		dbs.insertWord("", "Dial tone", "Tonalité", categoryId);
		dbs.insertWord("", "Ringtone", "Sonnerie", categoryId);
		dbs.insertWord("", "Hash key", "Touche dièse (UK)", categoryId);
		dbs.insertWord("", "Pound key", "Touche dièse (USA)", categoryId);
		dbs.insertWord("", "Switchboard", "Standard", categoryId);
		dbs.insertWord("", "To be on hold", "être en attente", categoryId);
		dbs.insertWord("", "To hold (the line)", "patienter", categoryId);
		dbs.insertWord("", "To put somebody through", "mettre quelqu'un en communication", categoryId);
		dbs.insertWord("", "Engaged tone", "tonalité occupée", categoryId);
		dbs.insertWord("", "To leave a message", "laisser un message", categoryId);
		dbs.insertWord("", "To hang up", "raccrocher", categoryId);
		dbs.insertWord("", "To put the phone down", "raccrocher", categoryId);
		dbs.insertWord("", "Area code", "indicatif régional", categoryId);
		dbs.insertWord("", "Ex-directory", "liste rouge (UK)", categoryId);
		dbs.insertWord("", "Unlisted", "liste rouge (USA)", categoryId);
		dbs.insertWord("", "Call charges", "tarif des appels", categoryId);
		dbs.insertWord("", "Itemized phone bill", "facture détaillée", categoryId);
		dbs.insertWord("", "Off-peak rate", "tarif heures creuses", categoryId);
		dbs.insertWord("", "Peak rate", "tarif heures pleines", categoryId);
		dbs.insertWord("", "Line rental", "abonnement", categoryId);
		dbs.insertWord("", "Phone company", "Opérateur téléphonique", categoryId);
		dbs.insertWord("", "Conférence call", "téléconférence", categoryId);
		dbs.insertWord("", "Initiator", "organisateur (de téléconférence)", categoryId);
		dbs.insertWord("", "Participant", "participant (à la téléconférence)", categoryId);
		dbs.insertWord("", "To set up a conference call", "démarrer une téléconférence", categoryId);
		dbs.insertWord("", "Refill card", "recharge (USA)", categoryId);
		dbs.insertWord("", "Top-up card", "recharge (UK)", categoryId);

		categoryId = dbs.insertCategory("Adverbes etc.", languageId);
		dbs.insertWord("", "To", "à / pour / jusqu'à / de", categoryId);
		dbs.insertWord("", "Too", "aussi", categoryId);
		dbs.insertWord("", "Today", "aujourd'hui", categoryId);
		dbs.insertWord("", "Tonight", "ce soir", categoryId);
		dbs.insertWord("", "Tomorrow", "demain", categoryId);
		dbs.insertWord("", "For", "pour", categoryId);
		dbs.insertWord("", "Forever", "pour toujours", categoryId);
		dbs.insertWord("", "Before", "avant", categoryId);
		dbs.insertWord("", "Because", "parce que", categoryId);
		dbs.insertWord("", "Any", "du / de la / n'importe lequel", categoryId);
		dbs.insertWord("", "Alternatively", "autrement", categoryId);
		dbs.insertWord("", "So", "donc", categoryId);
		dbs.insertWord("", "In order to", "afin de", categoryId);
		dbs.insertWord("", "So as to", "afin de", categoryId);
		dbs.insertWord("", "So that", "pour que", categoryId);
		dbs.insertWord("", "Likewise", "de même", categoryId);
		dbs.insertWord("", "Similarly", "de même", categoryId);
		dbs.insertWord("", "However", "cependant", categoryId);
		dbs.insertWord("", "Nevertheless", "néanmoins", categoryId);
		dbs.insertWord("", "Though", "pourtant", categoryId);
		dbs.insertWord("", "Such as", "tel que", categoryId);
		dbs.insertWord("", "Especially", "notamment", categoryId);
		dbs.insertWord("", "Mainly", "principalement", categoryId);
		dbs.insertWord("", "Also", "également", categoryId);
		dbs.insertWord("", "As well as", "ainsi que", categoryId);
		dbs.insertWord("", "Besides", "de plus", categoryId);
		dbs.insertWord("", "Also", "également", categoryId);
		dbs.insertWord("", "Rather", "plutôt", categoryId);
		dbs.insertWord("", "Perhaps", "peut-être", categoryId);

		categoryId = dbs.insertCategory("Réunions", languageId);
		dbs.insertWord("", "Board meeting", "conseil d'administration", categoryId);
		dbs.insertWord("", "Business meeting", "réunion d'affaires", categoryId);
		dbs.insertWord("", "Department meeting", "réunion de service", categoryId);
		dbs.insertWord("", "Staff meeting", "réunion du personnel", categoryId);
		dbs.insertWord("", "Team meeting", "réunion d'équipe", categoryId);
		dbs.insertWord("", "To ask", "demander", categoryId);
		dbs.insertWord("", "To demand", "exiger", categoryId);
		dbs.insertWord("", "To adjourn", "ajourner", categoryId);
		dbs.insertWord("", "To arrange", "organiser", categoryId);
		dbs.insertWord("", "To bring forward", "avancer", categoryId);
		dbs.insertWord("", "To call", "convoquer", categoryId);
		dbs.insertWord("", "To postpone", "reporter", categoryId);
		dbs.insertWord("", "To put back", "reporter", categoryId);
		dbs.insertWord("", "To set up", "préparer", categoryId);
		dbs.insertWord("", "To agree", "être d'accord", categoryId);
		dbs.insertWord("", "To disagree", "ne pas être d'accord", categoryId);
		dbs.insertWord("", "To brief someone", "informer quelqu'un", categoryId);
		dbs.insertWord("", "To suggest", "soumettre", categoryId);
		dbs.insertWord("", "Minutes", "procès-verbal", categoryId);
		dbs.insertWord("", "Proceeding", "compte-rendu", categoryId);
		dbs.insertWord("", "Agreement", "accord", categoryId);
		dbs.insertWord("", "Deadlock", "impasse", categoryId);
		dbs.insertWord("", "Proposal", "proposition", categoryId);
		dbs.insertWord("", "To stress the fact", "insister sur le fait", categoryId);
		dbs.insertWord("", "To draw (somebody) attention", "attirer l'attention", categoryId);
		dbs.insertWord("", "To follow", "suivre", categoryId);
		dbs.insertWord("", "Chair / chairperson", "président(e)", categoryId);
		dbs.insertWord("", "To chair a meeting", "présider une réunion", categoryId);
		dbs.insertWord("", "To move on", "avancer", categoryId);
		dbs.insertWord("", "To drop", "abandonner", categoryId);
		dbs.insertWord("", "To carry", "adopter", categoryId);
		dbs.insertWord("", "To reject", "rejeter", categoryId);
		dbs.insertWord("", "To highlight", "souligner", categoryId);
		dbs.insertWord("", "To outline", "résumer", categoryId);
		dbs.insertWord("", "To show", "montrer", categoryId);
		dbs.insertWord("", "Overview", "aperçu", categoryId);
		dbs.insertWord("", "To move on", "passer à", categoryId);
		dbs.insertWord("", "Data projector", "vidéoprojecteur", categoryId);
		dbs.insertWord("", "Sample", "échantillon", categoryId);
		dbs.insertWord("", "Screen", "écran", categoryId);
		dbs.insertWord("", "Slide", "diapositive", categoryId);
		dbs.insertWord("", "Visual aids", "support visuel", categoryId);
		dbs.insertWord("", "Whiteboard", "tableau blanc", categoryId);
		dbs.insertWord("", "To rise", "augmenter", categoryId);
		dbs.insertWord("", "To climb", "grimper", categoryId);
		dbs.insertWord("", "To jump", "grimper en flèche", categoryId);
		dbs.insertWord("", "To soar", "grimper en flèche", categoryId);
		dbs.insertWord("", "To go down", "diminuer", categoryId);
		dbs.insertWord("", "To fall", "diminuer", categoryId);
		dbs.insertWord("", "To decline", "diminuer", categoryId);
		dbs.insertWord("", "To reduce", "réduire", categoryId);
		dbs.insertWord("", "To collapse", "s'éffondrer", categoryId);
		dbs.insertWord("", "To rephrase", "reformuler", categoryId);
		dbs.insertWord("", "To tend to", "avoir tendance à", categoryId);

		categoryId = dbs.insertCategory("Carrière", languageId);
		dbs.insertWord("", "To apply (for a job)", "postuler", categoryId);
		dbs.insertWord("", "To accomplish", "accomplir", categoryId);
		dbs.insertWord("", "To achieved", "réaliser", categoryId);
		dbs.insertWord("", "To perform", "réaliser", categoryId);
		dbs.insertWord("", "To design", "concevoir", categoryId);
		dbs.insertWord("", "To expand", "élargir", categoryId);
		dbs.insertWord("", "To implement", "implémenter", categoryId);
		dbs.insertWord("", "To maintain", "entretenir", categoryId);
		dbs.insertWord("", "To evaluate", "estimer", categoryId);
		dbs.insertWord("", "To resolve", "résoudre", categoryId);
		dbs.insertWord("", "To review", "passer en revue", categoryId);
		dbs.insertWord("", "To develop", "mettre au point", categoryId);
		dbs.insertWord("", "To train", "former", categoryId);
		dbs.insertWord("", "Analytical", "esprit d'analyse", categoryId);
		dbs.insertWord("", "Skills", "compétences", categoryId);
		dbs.insertWord("", "Teamwork", "travail en équipe", categoryId);
		dbs.insertWord("", "Time management", "gestion du temps", categoryId);
		dbs.insertWord("", "Efficient", "efficace", categoryId);
		dbs.insertWord("", "Enthusiastic", "enthousiaste", categoryId);
		dbs.insertWord("", "Honest", "sincère", categoryId);
		dbs.insertWord("", "Reliable", "fiable", categoryId);
		dbs.insertWord("", "Self-motivating", "motivé", categoryId);
		dbs.insertWord("", "Self-sufficient", "autonome", categoryId);
		dbs.insertWord("", "Pay", "rémunération", categoryId);
		dbs.insertWord("", "Wage", "paie", categoryId);
		dbs.insertWord("", "Reward", "prime", categoryId);
		dbs.insertWord("", "Fringe benefit", "avantages en nature", categoryId);
		dbs.insertWord("", "Perks", " avantages en nature", categoryId);
	}
}
