package com.skula.school.models;

import com.skula.school.services.DatabaseService;

public class Data {
	public static void insert(DatabaseService dbs){
		//---- temps ------
		dbs.insertCategory("Adv. de temps", "allemand");
		dbs.insertWord("bald", "bientôt", "1");
		dbs.insertWord("bereits", "déjà", "1");
		dbs.insertWord("bisher", "jusqu'à  présent", "1");
		dbs.insertWord("danach", "après", "1");
		dbs.insertWord("davor", "avant", "1");
		dbs.insertWord("einst", "jadis", "1");
		dbs.insertWord("endlich", "enfin, à la fin", "1");
		dbs.insertWord("freitags", "le vendredi", "1");
		dbs.insertWord("gestern", "hier", "1");
		dbs.insertWord("immer", "toujours", "1");
		dbs.insertWord("inzwischen", "entre-temps", "1");
		dbs.insertWord("neulich", "récemment", "1");
		dbs.insertWord("nie", "jamais", "1");
		dbs.insertWord("oft", "souvent", "1");
		dbs.insertWord("regelmä$ig", "régulièrement", "1");
		dbs.insertWord("sofort", "tout de suite", "1");
		dbs.insertWord("stets", "constamment", "1");
		dbs.insertWord("täglich", "quotidiennement", "1");
		dbs.insertWord("zurzeit", "actuellement", "1");

		//----- lieu -----
		dbs.insertCategory("Adv. de lieu", "allemand");
		dbs.insertWord("aufwärts", "vers le haut", "2");
		dbs.insertWord("au$en", "à  l'extérieur", "2");
		dbs.insertWord("da", "là", "2");
		dbs.insertWord("dort", "là-bas", "2");
		dbs.insertWord("drinnen", "à  l'intérieur", "2");
		dbs.insertWord("fort", "au loin", "2");
		dbs.insertWord("hier", "ici", "2");
		dbs.insertWord("hierhin", "(vers/jusqu'à) ici", "2");
		dbs.insertWord("hinein", "à l'intérieur", "2");
		dbs.insertWord("hinten", "derrière", "2");
		dbs.insertWord("irgendwo", "quelque part", "2");
		dbs.insertWord("links", "à gauche", "2");
		dbs.insertWord("nebenan", "à côté", "2");
		dbs.insertWord("oberhalb", "au-dessus", "2");
		dbs.insertWord("überall", "partout", "2");
		dbs.insertWord("unten", "au-dessous", "2");
		dbs.insertWord("vorn", "devant", "2");

		//----- cause ------
		dbs.insertCategory("Adv. de cause", "allemand");
		dbs.insertWord("also", "ainsi, donc", "3");
		dbs.insertWord("anstandshalber", "par souci des convenances", "3");
		dbs.insertWord("dadurch", "par ce moyen", "3");
		dbs.insertWord("darum", "c'est pourquoi", "3");
		dbs.insertWord("demnach", "en conséquence", "3");
		dbs.insertWord("demzufolge", "par conséquent", "3");
		dbs.insertWord("deshalb", "pour cette raison, pour cela", "3");
		dbs.insertWord("folglich", "par conséquent", "3");
		dbs.insertWord("somit", "par conséquent", "3");

		//----- coordination -----
		dbs.insertCategory("Adv. de coordination", "allemand");
		dbs.insertWord("au$erdem", "en outre", "4");
		dbs.insertWord("danach", "ensuite", "4");
		dbs.insertWord("deshalb", "pour cette raison, c'est pourquoi", "4");
		dbs.insertWord("folglich", "par consÃ©quent", "4");
		dbs.insertWord("schlie$lich", "finalement, après tout", "4");
		dbs.insertWord("trotzdem", "malgré tout", "4");
		dbs.insertWord("zuvor", "auparavant, avant", "4");

		//----- maniere ------
		dbs.insertCategory("Adv. de maniere", "allemand");
		dbs.insertWord("anders", "autrement", "5");
		dbs.insertWord("äu$erst", "extrêmement", "5");
		dbs.insertWord("beinahe", "presque, quasi", "5");
		dbs.insertWord("bekanntlich", "comme chacun sait", "5");
		dbs.insertWord("ebenfalls", "aussi", "5");
		dbs.insertWord("fast", "presque", "5");
		dbs.insertWord("folgenderma$en", "de la manière suivante", "5");
		dbs.insertWord("ganz", "tout, entièrement", "5");
		dbs.insertWord("genauso", "de même", "5");
		dbs.insertWord("genug", "assez", "5");
		dbs.insertWord("gern", "volontiers", "5");
		dbs.insertWord("grö$tenteils", "en majeure partie, majoritairement", "5");
		dbs.insertWord("hauptsächlich", "surtout", "5");
		dbs.insertWord("kaum", "guère, à  peine", "5");
		dbs.insertWord("leider", "malheureusement", "5");
		dbs.insertWord("möglicherweise", "peut-être", "5");
		dbs.insertWord("reihenweise", "les uns après les autres", "5");
		dbs.insertWord("sehr", "très", "5");
		dbs.insertWord("so", "ainsi", "5");
		dbs.insertWord("vielleicht", "peut-être", "5");
		dbs.insertWord("wirklich", "vraiment", "5");
		
		// voc 1
		dbs.insertCategory("La personnalité", "allemand");
		dbs.insertWord("die Adresse (n)", "l'adresse", "6");
		dbs.insertWord("allein", "seul", "6");
		dbs.insertWord("das Alter (-)", "l’âge", "6");
		dbs.insertWord("die Anschrift (en)", "l'adresse", "6");
		dbs.insertWord("das Ausland", "le pays étranger", "6");
		dbs.insertWord("der Ausländer (-)", "l’étranger", "6");
		dbs.insertWord("der Ausweis (e)", "la carte d'identité", "6");
		dbs.insertWord("der Beruf (e)", "le métier", "6");
		dbs.insertWord("der Bruder (¨)", "le frère", "6");
		dbs.insertWord("der/die Deutsche (n)", "l'Allemand(e)", "6");
		dbs.insertWord("dreisprachig", "trilingue", "6");
		dbs.insertWord("das Einzelkind (er)", "l’enfant unique", "6");
		dbs.insertWord("Eltern (PLUR)", "les parents", "6");
		dbs.insertWord("die E-Mail-Adresse (n)", "l'adresse électronique", "6");
		dbs.insertWord("das Enkelkind (er)", "le petit-fils", "6");
		dbs.insertWord("der/die Erwachsene (n)", "adulte", "6");
		dbs.insertWord("die Familie (n)", "la famille", "6");
		dbs.insertWord("der Familienname (n)", "le nom de famille", "6");
		dbs.insertWord("der Fragebogen (-)", "le questionnaire", "6");
		dbs.insertWord("der Franzose (n)", "le Français", "6");
		dbs.insertWord("die Französin (nen)", "la Française", "6");
		dbs.insertWord("die Frau (en)", "la femme", "6");
		dbs.insertWord("die Fremdsprache (n)", "la langue étrangère", "6");
		dbs.insertWord("der Führerschein (e)", "le permis de conduire", "6");
		dbs.insertWord("geboren", "né", "6");
		dbs.insertWord("der Geburtsort (e)", "lieu de naissance", "6");
		dbs.insertWord("geschieden", "divorcé", "6");
		dbs.insertWord("Geschwister (PLUR)", "frère(s) et soeur(s)", "6");
		dbs.insertWord("getrennt", "séparé", "6");
		dbs.insertWord("Gro$eltern (PLUR)", "les grands-parents", "6");
		dbs.insertWord("die Gro$mutter (¨)", "la grand-mère", "6");
		dbs.insertWord("der Gro$vater (¨)", "le grand-père", "6");
		dbs.insertWord("die Handynummer (n)", "le numéro", "6");
		dbs.insertWord("die Hausnummer (n)", "le numéro de la maison", "6");
		dbs.insertWord("hei$en", "s'appeler", "6");
		dbs.insertWord("der/die Jugendliche (n)", "le jeune", "6");
		dbs.insertWord("der Junge (n)", "le garçon", "6");
		dbs.insertWord("das Kind (er)", "l’enfant", "6");
		dbs.insertWord("das Land (¨er)", "le pays", "6");
		dbs.insertWord("leben", "vivre", "6");
		dbs.insertWord("der Lebenslauf (¨e)", "le C.V.", "6");
		dbs.insertWord("ledig", "célibataire", "6");
		dbs.insertWord("das Mädchen (-)", "la fillette, la jeune fille", "6");
		dbs.insertWord("der Mann (¨er)", "l’homme", "6");
		dbs.insertWord("die Mutter (¨)", "la mère", "6");
		dbs.insertWord("die Muttersprache (n)", "la langue maternelle", "6");
		dbs.insertWord("der Nachname (n)", "le nom de famille", "6");
		dbs.insertWord("der Name (n)", "le nom", "6");
		dbs.insertWord("nennen", "nommer, citer", "6");
		dbs.insertWord("die Oma (s)", "la mamie", "6");
		dbs.insertWord("der Onkel (s)", "l’oncle", "6");
		dbs.insertWord("der Opa (s)", "le papi", "6");
		dbs.insertWord("der Österreicher (-)", "l’Autrichien", "6");
		dbs.insertWord("die Papiere", "les papiers d'identité", "6");
		dbs.insertWord("der Pass (¨e)", "le passeport", "6");
		dbs.insertWord("die Postleitzahl (en)", "le code postal", "6");
		dbs.insertWord("der Schweizer (-)", "la Suisse", "6");
		dbs.insertWord("die Schwester (n)", "la soeur", "6");
		dbs.insertWord("der Sohn (¨e)", "le fils", "6");
		dbs.insertWord("der Staatsbürger (-)", "le citoyen", "6");
		dbs.insertWord("die Stadt (¨e)", "la ville", "6");
		dbs.insertWord("der Stammbaum (¨e)", "l’arbre généalogique", "6");
		dbs.insertWord("der Steckbrief (e) (ici)", "la fiche signalétique", "6");
		dbs.insertWord("die Stra$e (n)", "la rue", "6");
		dbs.insertWord("die Tante (n)", "la tante", "6");
		dbs.insertWord("die Telefonnummer (n)", "le numéro de téléphone", "6");
		dbs.insertWord("die Tochter (¨)", "la fille", "6");
		dbs.insertWord("die Unterschrift (en)", "la signature", "6");
		dbs.insertWord("der Vater (¨)", "le père", "6");
		dbs.insertWord("verheiratet", "marié", "6");
		dbs.insertWord("verwandt (sein)", "avoir un lien de parenté", "6");
		dbs.insertWord("der/die Verwandte (n)", "le parent", "6");
		dbs.insertWord("die Verwandtschaft (en)", "la famille", "6");
		dbs.insertWord("der Vorname (n)", "le prénom", "6");
		dbs.insertWord("vorstellen (sich)", "(se) présenter", "6");
		dbs.insertWord("wohnen", "habiter", "6");
		dbs.insertWord("der Wohnort (e)", "lieu de résidence", "6");
		dbs.insertWord("zweisprachig", "bilingue", "6");
		dbs.insertWord("die Zwillinge", "les jumeaux", "6");
		
		dbs.insertCategory("Renseignements personnels", "allemand");
		dbs.insertWord("ähnlich", "semblable, ressemblant", "7");
		dbs.insertWord("die Ähnlichkeit", "la ressemblance", "7");
		dbs.insertWord("albern", "puéril, idiot", "7");
		dbs.insertWord("alt", "vieux", "7");
		dbs.insertWord("arm", "pauvre", "7");
		dbs.insertWord("arm", "malheureux", "7");
		dbs.insertWord("das Auge (n)", "l'oeil", "7");
		dbs.insertWord("aussehen", "avoir l'air", "7");
		dbs.insertWord("das Aussehen (-)", "l'apparence physique", "7");
		dbs.insertWord("begabt", "doué", "7");
		dbs.insertWord("bekannt", "connu", "7");
		dbs.insertWord("beliebt", "apprécié", "7");
		dbs.insertWord("bescheiden", "modeste", "7");
		dbs.insertWord("blond", "blond", "7");
		dbs.insertWord("böse", "méchant", "7");
		dbs.insertWord("brav", "sage, raisonnable", "7");
		dbs.insertWord("die Brille (n)", "les lunettes", "7");
		dbs.insertWord("die Charaktereigenschaft", "(entr)ait de caractère", "7");
		dbs.insertWord("dick", "gros", "7");
		dbs.insertWord("dunkel", "sombre, foncé", "7");
		dbs.insertWord("dünn", "mince", "7");
		dbs.insertWord("ehrlich", "honnête", "7");
		dbs.insertWord("die Eigenschaft (en)", "la qualité, la particularité", "7");
		dbs.insertWord("empfindlich", "susceptible, sensible", "7");
		dbs.insertWord("energisch", "énergique, vif", "7");
		dbs.insertWord("ernst", "sérieux", "7");
		dbs.insertWord("faul", "paresseux", "7");
		dbs.insertWord("flei$ig", "travailleur, zélé, assidu", "7");
		dbs.insertWord("frech", "insolent", "7");
		dbs.insertWord("der Freund (e)", "l'ami", "7");
		dbs.insertWord("freundlich", "aimable, amical", "7");
		dbs.insertWord("die Frisur (en)", "la coiffure", "7");
		dbs.insertWord("geduldig", "patient", "7");
		dbs.insertWord("gemein", "méchant, odieux", "7");
		dbs.insertWord("gepflegt", "soigné, bien mis", "7");
		dbs.insertWord("gerecht", "juste", "7");
		dbs.insertWord("geschickt", "adroit", "7");
		dbs.insertWord("glücklich", "heureux", "7");
		dbs.insertWord("grau", "gris", "7");
		dbs.insertWord("gro$", "grand", "7");
		dbs.insertWord("gut", "bien, bon", "7");
		dbs.insertWord("das Haar (e)", "le(s) cheveu(x)", "7");
		dbs.insertWord("hart", "dur", "7");
		dbs.insertWord("hässlich", "laid", "7");
		dbs.insertWord("hell", "clair", "7");
		dbs.insertWord("hilfsbereit", "serviable", "7");
		dbs.insertWord("das Hobby (Hobbys)", "le loisir préféré", "7");
		dbs.insertWord("höflich", "poli", "7");
		dbs.insertWord("hübsch", "joli", "7");
		dbs.insertWord("humorvoll", "plein d'humour", "7");
		dbs.insertWord("interessieren (sich)", "s'intéresser à ", "7");
		dbs.insertWord("interessiert", "intéressé", "7");
		dbs.insertWord("jugendlich", "adolescent", "7");
		dbs.insertWord("jung", "jeune", "7");
		dbs.insertWord("klein", "petit", "7");
		dbs.insertWord("klug", "intelligent", "7");
		dbs.insertWord("komisch", "drôle", "7");
		dbs.insertWord("kontaktfreudig", "qui aime les contacts", "7");
		dbs.insertWord("kräftig", "fort", "7");
		dbs.insertWord("lächerlich", "ridicule", "7");
		dbs.insertWord("lieb", "gentil", "7");
		dbs.insertWord("lustig", "drôle, gai", "7");
		dbs.insertWord("mutig", "courageux", "7");
		dbs.insertWord("naiv", "naïf", "7");
		dbs.insertWord("nervös", "nerveux", "7");
		dbs.insertWord("nett", "gentil", "7");
		dbs.insertWord("neugierig", "curieux", "7");
		dbs.insertWord("ordentlich", "soigneux", "7");
		dbs.insertWord("der Pechvogel", "le malchanceux", "7");
		dbs.insertWord("die Persönlichkeit (en)", "la personnalité", "7");
		dbs.insertWord("reich", "riche", "7");
		dbs.insertWord("ruhig", "tranquille, calme", "7");
		dbs.insertWord("schlank", "mince", "7");
		dbs.insertWord("schlau", "malin, intelligent", "7");
		dbs.insertWord("schmal", "étroit", "7");
		dbs.insertWord("schön", "beau", "7");
		dbs.insertWord("schüchtern", "timide", "7");
		dbs.insertWord("schwach", "faible", "7");
		dbs.insertWord("schwarz", "noir", "7");
		dbs.insertWord("selbstsicher", "sûr de soi", "7");
		dbs.insertWord("sportlich", "sportif", "7");
		dbs.insertWord("stark", "fort", "7");
		dbs.insertWord("der Steckbrief (e)", "(ici) la fiche signalétique", "7");
		dbs.insertWord("stolz", "fier", "7");
		dbs.insertWord("streng", "sévère", "7");
		dbs.insertWord("sü$", "mignon, gentil, touchant", "7");
		dbs.insertWord("sympathisch", "sympathique", "7");
		dbs.insertWord("tolerant", "tolérant", "7");
		dbs.insertWord("treu", "fidèle, loyal", "7");
		dbs.insertWord("unternehmungslustig", "entreprenant", "7");
		dbs.insertWord("unverschämt", "effronté, impertinent", "7");
		dbs.insertWord("vergesslich", "oublieux, distrait", "7");
		dbs.insertWord("vernünftig", "raisonnable", "7");
		dbs.insertWord("verständnisvoll", "compréhensif", "7");
		dbs.insertWord("das Vorbild (er)", "le modèle", "7");
		dbs.insertWord("vorsichtig", "prudent", "7");
		dbs.insertWord("weich", "sensible", "7");
		dbs.insertWord("wei$", "blanc", "7");
		dbs.insertWord("witzig", "drôle", "7");
		dbs.insertWord("zufrieden", "satisfait, content", "7");
		dbs.insertWord("zuverlässig", "fiable", "7");
	}
}
